apiVersion: v1
kind: Pod
metadata:
   name: confusion
spec:
   containers:
      - name: confusion
        image: confusion
        imagePullPolicy: Never
        ports:
          - containerPort: 3000
